language: python
jobs:
  include:
    - if: type = pull_request
      script:
        - echo "Validate Pull Request"

    - if: type = push AND NOT branch = master
      script:
        - echo "Ordinary push"
        
    - if: type = push AND branch = master
      install:
        - pip install -r ./scripts/travis/requirements.txt
      script:
        - python ./scripts/travis/deploy.py