language: node_js
node_js:
    - "8"
script:
    - npm install
    - npm install -g firebase-tools
    - npm run-script build
    - echo “Deploy!!”
after_success:
    - firebase deploy --token $FIREBASE_TOKEN.
