language: python
jobs:
  include:
    - if: type = pull_request
      script:
        - echo "Validate Pull Request"

    - if: type = push AND NOT branch = master
      script:
        - echo "Ordinary push"
        - python ./scripts/travis_env_test.py

    - if: type = push AND branch = master
      install:
        - pip install -r requirements.txt
      script:
        - python ./scripts/travis.py