language: node_js
node_js:
    - "stable"
script:
    - npm run-script build
    - echo “Deploy!!”
install:
    - npm install -g firebase-tools
after_success:
    - firebase deploy --token $FIREBASE_TOKEN.
