name: Deploy
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: Display Python version
      run: python3 -c "import sys; print(sys.version)"

    - name: Install packages
      run: |
        python3 -m pip install setuptools wheel
        python3 -m pip install -r ./scripts/travis/requirements.txt

    - name: Populate Database
      run: python3 ./scripts/travis/deploy.py
