name: Deploy
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Populate Database
      run: |
        pip install -r ./scripts/travis/requirements.txt
        python ./scripts/travis/deploy.py
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
